### ISSUE TITLE
latest serverless 

### ISSUE THREAD

**Issue by pdutt111** [microapps/MoonMail#199]
I'm trying to figure out how to get this to work with the latest serverless, but im unable to find a reliable tut. The older serverless is deprecated and its hard to find answers to questions for the specific version that moonmail requires

**Comment by ccverak** [comment]
Hi @pdutt111! I'm sorry to say that we currently don't support serverless 1.x.x versions, the newer approach it's radically different from what we are using now so it won't work without doing changes. However, as serverless is just a deployment tool, only changes in functions configuration not it the code are required to do the migration, we'd love to see contributions on this matter.

This is how function configuration should be approached in the 1.x version:

https://serverless.com/framework/docs/providers/aws/guide/serverless.yml

And this is how we are doing it right now:

https://serverless.readme.io/docs/project-structure

Check our Wiki for more details: https://github.com/microapps/MoonMail/wiki

**Comment by StaymanHou** [comment]
+1

**Comment by Karloski** [comment]
You might want to change the readme so that it does not say "version 0.5.2 or higher", otherwise people might get confused and think your program supports version 0.5.2 or higher.

**Comment by geoff-ellison** [comment]
I still cannot get the project to deploy on sls v0.5, and because there is limited debug/verbose capability, I can't see the error (can't see it in AWS either, because the CloudFormation stack gets deleted automatically after deploy fails). It would be very valuable to me if v1+ was supported, because then (at the very least) I'd be able to debug the deployment.
P.S. @ccverak, if nothing higher than sls v0.5 is supported, why is this issue closed?
Thanks all.
