### ISSUE TITLE
README syntax invalid

### ISSUE THREAD

**Issue by ayb** [microapps/MoonMail#256]
For Serverless 1.25.0

The command

`sls project init -c -n your-lower-case-project-name`

is invalid

Yielding the response "Serverless command "project" not found"

**Comment by ccverak** [comment]
Hey @ayb, thanks for showing interest in the project. The error you are receiving is due to a version mismatch in the serverless package, we are still using serverless 0.5 for most of the codebase, this means that using a greater version will not work. In order to solve the issue, you will have to explicitly specify the required version in the npm install command ie: `npm install serverless@0.5.6`.
